### ISSUE TITLE
break used outside a loop

### ISSUE THREAD

**Issue by indiajoe** [laurenwillett/nuts-for-ysos#2]
This `break` command is outside a python loop. Hence, it raises compilation errors.
https://github.com/laurenwillett/nuts-for-ysos/blob/ee12ead98f0d201ff68f078678ec261bcc86e021/pymc_fitter_new.py#L149

Did you mean to do a  `return None` instead?

**Comment by laurenwillett** [comment]
ah sorry yeah I fixed that in my code but apparently forgot to update it here in github. Fixed now
